# Generated by Django 6.0 on 2025-12-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], max_length=20)),
                ('ai_response', models.TextField()),
                ('publish_mode', models.CharField(choices=[('suggestion', 'Suggestion'), ('auto', 'Automatique')], default='suggestion', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.ticket')),
            ],
        ),
    ]
