# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('marche_public', 'Marché Public'), ('entreprise', 'Entreprise'), ('offre_emploi', "Offre d'Emploi")], max_length=20)),
                ('project_type', models.CharField(blank=True, choices=[('GTB', 'GTB (Gestion Technique du Bâtiment)'), ('GTEB', 'GTEB (Génie Technique Électrique du Bâtiment)'), ('CVC', 'CVC (Chauffage Ventilation Climatisation)'), ('supervision', 'Supervision Bâtiment'), ('electricite', 'Électricité Bâtiment'), ('automatisme', 'Automatisme'), ('mixte', 'Mixte')], max_length=20, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Maroc', max_length=100)),
                ('market_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('market_url', models.URLField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, choices=[('hopital', 'Hôpital'), ('industrie', 'Industrie'), ('tertiaire', 'Tertiaire'), ('public', 'Public'), ('residentiel', 'Résidentiel'), ('autre', 'Autre')], max_length=20, null=True)),
                ('company_size', models.CharField(choices=[('petite', 'Petite (< 50 employés)'), ('moyenne', 'Moyenne (50-250 employés)'), ('grande', 'Grande (> 250 employés)'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('temperature', models.CharField(choices=[('froid', 'Froid (0-39)'), ('tiede', 'Tiède (40-69)'), ('chaud', 'Chaud (70-100)')], default='froid', max_length=10)),
                ('score_justification', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('keywords_found', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_contacted', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-score', '-created_at'], name='core_lead_score_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['temperature'], name='core_lead_tempera_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['country', 'city'], name='core_lead_country_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project_type'], name='core_lead_project_idx'),
        ),
    ]

