# Generated by Django 6.0 on 2025-12-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='core_lead_score_8c3ca9_idx',
            old_name='core_lead_score_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='core_lead_tempera_c1e9c4_idx',
            old_name='core_lead_tempera_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='core_lead_country_3300df_idx',
            old_name='core_lead_country_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='core_lead_project_a807d7_idx',
            old_name='core_lead_project_idx',
        ),
    ]
