# Generated by Django 6.0 on 2026-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_lead_score_cr_idx_core_lead_score_8c3ca9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanalysis',
            name='intention',
            field=models.TextField(),
        ),
    ]
