# Generated by Django 6.0 on 2026-01-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticketanalysis_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('ouvert', 'Ouvert'), ('rappel_en_attente', 'Rappel en attente'), ('en_attente_de_cloture', 'En attente de clôture'), ('cloture', 'Clôturé')], max_length=25),
        ),
    ]
